"""empty message

Revision ID: 70baa1d7c514
Revises: 
Create Date: 2023-06-11 12:08:53.071776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70baa1d7c514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_sku_catalogo')
    op.drop_table('sku_precio')
    op.drop_table('c_customer')
    op.drop_table('temp_tela_util_merma')
    op.drop_table('orden_envasado_sku')
    op.drop_table('tb_imagen')
    op.drop_table('precios_proveedor')
    op.drop_table('tb_color')
    op.drop_table('temp_os_conforme_disponible')
    op.drop_table('orden_despacho_skupack')
    op.drop_table('tb_material')
    op.drop_table('tb_kit')
    op.drop_table('materia_prima')
    op.drop_table('temp_no_conforme_disponible')
    op.drop_table('insumo_orden_corte')
    op.drop_table('supplier')
    op.drop_table('ecommerce_tol_conversion')
    op.drop_table('c_activity')
    op.drop_table('orden_de_corte')
    op.drop_table('tb_tela')
    op.drop_table('orden_de_servicio')
    op.drop_table('categoria')
    op.drop_table('c_customer_address')
    op.drop_table('tb_peso_efectivo')
    op.drop_table('tb_usuarios')
    op.drop_table('recepcion')
    op.drop_table('orden_envasado')
    op.drop_table('pop_sku_pack_readable')
    op.drop_table('f_users')
    op.drop_table('tb_pack')
    op.drop_table('sku_pack')
    op.drop_table('orden_de_servicio_sku')
    op.drop_table('sku')
    op.drop_table('tb_servicio_taller')
    op.drop_table('c_stage_status')
    op.drop_table('status_orden_servicio')
    op.drop_table('tb_yk_topic')
    op.drop_table('tb_sku_corte')
    op.drop_table('tb_temp_movimiento')
    op.drop_table('tb_peso_consumo')
    op.drop_table('orden_despacho')
    op.drop_table('tb_talla')
    op.drop_table('orden_envasado_sku_staging')
    op.drop_table('c_office_user')
    op.drop_table('woo_order_b2c_cliente')
    op.drop_table('woo_order_b2c_producto')
    op.drop_table('producto_noconforme')
    op.drop_table('stock_skupack')
    op.drop_table('products')
    op.drop_table('c_service')
    op.drop_table('orden_despacho_sku')
    op.drop_table('color')
    op.drop_table('stock')
    op.drop_table('c_service_stage')
    op.drop_table('enviados_a_servicio')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=70),
               nullable=False)

    with op.batch_alter_table('tut__user_model', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tut__user_model', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=70),
               nullable=True)

    op.create_table('enviados_a_servicio',
    sa.Column('alm_corte_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_corte', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('orden_servicio', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('sku_readable', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cantidad_units_enviadas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_de_envio', sa.DATE(), nullable=False),
    sa.Column('peso_kg', mysql.DOUBLE(precision=8, scale=2, asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('alm_corte_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('c_service_stage',
    sa.Column('id_service_stage', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('stage_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35), nullable=False),
    sa.Column('id_service', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_service_stage'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stock',
    sa.Column('stock_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_recepcion', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('id_despacho', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cantidad', mysql.DOUBLE(precision=8, scale=2, asdecimal=True), nullable=False),
    sa.Column('nombre_operacion', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('locacion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('comentario', mysql.VARCHAR(length=350), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('stock_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('color',
    sa.Column('color_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('img_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('color_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_despacho_sku',
    sa.Column('orden_despacho_sku_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cod_orden_despacho', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('cantidad', mysql.DOUBLE(precision=8, scale=2, asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('orden_despacho_sku_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('c_service',
    sa.Column('id_service', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('service_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35), nullable=False),
    sa.PrimaryKeyConstraint('id_service'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('stock_skupack',
    sa.Column('stock_skupack_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_recepcion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('id_despacho', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=20), autoincrement=False, nullable=False),
    sa.Column('nombre_operacion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('locacion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('comentario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=350), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('stock_skupack_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('producto_noconforme',
    sa.Column('noconforme_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('recepcion_cod', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('tipo_accion', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('noconforme_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('woo_order_b2c_producto',
    sa.Column('row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('nombre_sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('talla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=50), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('woo_order_b2c_cliente',
    sa.Column('row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nombre_cliente', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('fecha_orden', sa.DATE(), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('c_office_user',
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('nivel_acceso', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_envasado_sku_staging',
    sa.Column('oe_sku_staging_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cod_oe', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('cantidad', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.PrimaryKeyConstraint('oe_sku_staging_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_talla',
    sa.Column('talla_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo_talla', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('talla_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_despacho',
    sa.Column('orden_despacho_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cod_orden_despacho', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_despacho', sa.DATE(), nullable=False),
    sa.Column('tipo_despacho', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('nombre_cliente', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('nota_pedido', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('detalles', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('orden_despacho_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_peso_consumo',
    sa.Column('row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('sku_tela', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('color_sku_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('peso_consumo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_temp_movimiento',
    sa.Column('mov_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_mov', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('orden', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('sku', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('cantidad', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('descripcion_mov', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('comentario', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8_unicode_ci', length=25), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8_unicode_ci', length=15), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('mov_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_sku_corte',
    sa.Column('sku_corte_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sku_corte', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tipo_sku', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_readable', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('spec', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('talla', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('componente', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_catalogo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('sku_corte_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_yk_topic',
    sa.Column('rec_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('topic', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('complete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rec_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('status_orden_servicio',
    sa.Column('status_os_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_servicio', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('status_os_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('c_stage_status',
    sa.Column('id_status', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('status_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35), nullable=False),
    sa.PrimaryKeyConstraint('id_status'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_servicio_taller',
    sa.Column('servicio_taller_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('etapa', mysql.INTEGER(display_width=10), autoincrement=False, nullable=False),
    sa.Column('nombre_ope', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ruta_taller', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('servicio_taller_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sku',
    sa.Column('sku_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo_sku', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('categoria', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('nombre_item', mysql.VARCHAR(charset='utf8', length=255), nullable=False),
    sa.Column('sku_readable', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('color', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('especificaciones', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('precio', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('talla', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('marca', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('uom', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('locacion_esperada', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('color_sku', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('ruta', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('sku_catalogo', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('sku_catalogo_readable', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('color_sku_catalogo', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('sku_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_de_servicio_sku',
    sa.Column('orden_serv_sku_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_servicio', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('orden_corte', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('sku', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('sku_readable', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cantidad', mysql.DOUBLE(precision=8, scale=2, asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('orden_serv_sku_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('sku_pack',
    sa.Column('pack_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('tipo_sku_child', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('categoria_child', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('sku_child', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('cantidad_child', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('talla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('pack_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_pack',
    sa.Column('pack_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo_pack', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('combinacion', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('tipo_sku', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_child', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cantidad', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('talla', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('pack_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('f_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pop_sku_pack_readable',
    sa.Column('poppack_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('talla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('skupack_readable', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=350), nullable=True),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('poppack_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_envasado',
    sa.Column('orden_envasado_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cod_oe', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=False),
    sa.Column('fecha_pack', sa.DATE(), nullable=False),
    sa.Column('tipo_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('detalles', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('asignado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.PrimaryKeyConstraint('orden_envasado_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recepcion',
    sa.Column('recepcion_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_servicio', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=35), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('estado_sku', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('fecha_recibida', sa.DATE(), nullable=False),
    sa.Column('locacion', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('comentario', mysql.VARCHAR(length=350), nullable=True),
    sa.Column('usuario', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('gestionado_en_nueva_os', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('nueva_orden_servicio', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('recepcion_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_usuarios',
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nivel_acceso', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_peso_efectivo',
    sa.Column('row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('categoria_sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('color_sku_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('peso_efectivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('c_customer_address',
    sa.Column('address_row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_customer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('address_info', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('address_city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('po_box', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('address_region', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('addressPostalCode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('address_row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categoria',
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('marca', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('talla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('material_envase', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('categoria_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_de_servicio',
    sa.Column('orden_servicio_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_servicio', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('fecha_orden_servicio', sa.DATE(), nullable=False),
    sa.Column('proveedor', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('fecha_envio', sa.DATE(), nullable=False),
    sa.Column('recibo_fecha_desde', sa.DATE(), nullable=False),
    sa.Column('recibo_fecha_hasta', sa.DATE(), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('orden_servicio_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_tela',
    sa.Column('tela_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo_sku', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_tela', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('uom', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('tela_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_de_corte',
    sa.Column('corte_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_corte', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('fecha_emision', sa.DATE(), nullable=False),
    sa.Column('fecha_de_corte', sa.DATE(), nullable=False),
    sa.Column('categoria_sku', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('sku_readable', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cant_units', mysql.DOUBLE(precision=8, scale=2, asdecimal=True), nullable=False),
    sa.Column('peso_kg', mysql.DOUBLE(precision=8, scale=2, asdecimal=True), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('corte_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('c_activity',
    sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('comment_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('comment', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('id_customer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('usuario_nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35), nullable=False),
    sa.Column('office', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('id_service', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_stage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_stage_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('registered_num', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('activity_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ecommerce_tol_conversion',
    sa.Column('row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('eco_sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('eco_talla', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('eco_color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('tol_sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('tol_cantidad', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=35), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('supplier',
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('codigo', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=25), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('insumo_orden_corte',
    sa.Column('insumo_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_corte', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('fecha_emision', sa.DATE(), nullable=False),
    sa.Column('string_categ_sku', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('color_rollo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cant_solicitada_kg', mysql.DOUBLE(precision=8, scale=2, asdecimal=True), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('insumo_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('temp_no_conforme_disponible',
    sa.Column('recepcion_id', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.Column('orden_servicio', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('sku_catalogo_readable', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('cantidad', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('fecha_recibida', sa.DATE(), nullable=False),
    sa.Column('comentario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('proveedor', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('ruta', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('gestionado_en_nueva_os', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('sku_catalogo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('validado_enviado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('materia_prima',
    sa.Column('mat_prima_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mat_prima_sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('uom', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('cantidad_master', mysql.DECIMAL(precision=9, scale=3), nullable=False),
    sa.Column('precio_master', mysql.DECIMAL(precision=9, scale=3), nullable=False),
    sa.Column('precio_master_desde', sa.DATE(), nullable=False),
    sa.Column('precio_master_hasta', sa.DATE(), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('mat_prima_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_kit',
    sa.Column('kit_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sku_kit', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tipo_sku', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cantidad', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('talla', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('kit_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_material',
    sa.Column('material_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo_sku', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_material', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('material_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_despacho_skupack',
    sa.Column('orden_despacho_skupack_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cod_orden_despacho', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('cantidad', mysql.DECIMAL(precision=9, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('orden_despacho_skupack_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('temp_os_conforme_disponible',
    sa.Column('row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('fecha_emision', sa.DATE(), nullable=False),
    sa.Column('fecha_de_corte', sa.DATE(), nullable=False),
    sa.Column('categoria_sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('sku_readable', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('cant_units', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('peso_kg', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('ruta', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_color',
    sa.Column('color_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tipo_color', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('color_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('precios_proveedor',
    sa.Column('precio_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('categoria_sku', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('proveedor', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('costo_unitario_conIGV', mysql.DECIMAL(precision=9, scale=3), nullable=False),
    sa.Column('costo_unitario_sinIGV', mysql.DECIMAL(precision=9, scale=3), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('precio_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_imagen',
    sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_servicio', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8_unicode_ci', length=355), nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('estado', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('orden_envasado_sku',
    sa.Column('oe_sku_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cod_oe', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('sku_pack', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('cantidad', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.PrimaryKeyConstraint('oe_sku_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('temp_tela_util_merma',
    sa.Column('row_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orden_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('categoria_sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('sku_tela', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('nombre_item', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('color_sku_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False),
    sa.Column('peso_efectivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('peso_consumo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('ratio_utilizacion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('ratio_merma', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('unidades_corte', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('row_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('c_customer',
    sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('random_num', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('phone', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('email', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('id_driver_license', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('id_social_security', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('id_passport', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('estado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('id_usuario_office', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sku_precio',
    sa.Column('sku_precio_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('codigo_supplier', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('costo_fecha_desde', sa.DATE(), nullable=False),
    sa.Column('costo_fecha_hasta', sa.DATE(), nullable=False),
    sa.Column('costo', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('sku_precio_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_sku_catalogo',
    sa.Column('sku_catalogo_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sku_catalogo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tipo_sku', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sku_readable', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('spec', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('talla', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('sku_catalogo_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
